#!/bin/bash
# Creates CherryTree++.app: a small launcher bundle for this checkout's build/cherrytree, so the
# fork's build (with its fixes) can be started from Finder, Spotlight or the Dock.
#
# Usage: claude/macos/make-app.sh [destination-dir]      (default: ~/Applications)
#
# The bundle only launches the build; rebuild with ./build.sh and the app picks it up. Settings
# are shared with the stock CherryTree.app (same config dir), so preferences such as
# "Reload After External Update" carry over.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "${HERE}/../.." && pwd)"
DEST="${1:-${HOME}/Applications}"
APP="${DEST}/CherryTree++.app"
NAME="CherryTree++"
BUNDLE_ID="com.github.bigbadbuff.cherrytree-plusplus"
ICON_SOURCE="${REPO}/icons/cherrytree.svg"
VERSION="$(head -1 "${REPO}/debian/changelog" | sed -E 's/.*\(([0-9]+\.[0-9]+\.[0-9]+).*/\1/')"

for tool in rsvg-convert sips iconutil; do
  command -v "${tool}" > /dev/null || { echo "missing ${tool} (brew install librsvg)" >&2; exit 1; }
done

STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT

# --- icon: render the SVG once, then scale into a standard .iconset
ICONSET="${STAGE}/${NAME}.iconset"
mkdir -p "${ICONSET}"
rsvg-convert -w 1024 -h 1024 "${ICON_SOURCE}" -o "${STAGE}/icon_1024.png"
for size in 16 32 128 256 512; do
  sips -z "${size}" "${size}" "${STAGE}/icon_1024.png" --out "${ICONSET}/icon_${size}x${size}.png" > /dev/null
  double=$((size * 2))
  sips -z "${double}" "${double}" "${STAGE}/icon_1024.png" --out "${ICONSET}/icon_${size}x${size}@2x.png" > /dev/null
done

# --- bundle
rm -rf "${APP}"
mkdir -p "${APP}/Contents/MacOS" "${APP}/Contents/Resources"
iconutil -c icns "${ICONSET}" -o "${APP}/Contents/Resources/${NAME}.icns"

cat > "${APP}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${NAME}</string>
  <key>CFBundleDisplayName</key><string>${NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleExecutable</key><string>${NAME}</string>
  <key>CFBundleIconFile</key><string>${NAME}.icns</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundleVersion</key><string>${VERSION}</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
PLIST

cat > "${APP}/Contents/MacOS/${NAME}" <<LAUNCHER
#!/bin/bash
# Generated by claude/macos/make-app.sh: runs the CherryTree build of ${REPO}
BIN="${REPO}/build/cherrytree"
if [ ! -x "\${BIN}" ]; then
  message="Build it first: cd '${REPO}' && ./build.sh release notests"
  echo "${NAME}: \${BIN} not found. \${message}" >&2
  [ -t 2 ] || osascript -e "display alert \"${NAME} is not built\" message \"\${message}\"" > /dev/null
  exit 1
fi
# share settings with the stock CherryTree.app, and give GTK a UTF-8 locale when started from Finder
export XDG_CONFIG_HOME="\${XDG_CONFIG_HOME:-\${HOME}/Library/Application Support/net.giuspen.CherryTree}"
export LANG="\${LANG:-en_US.UTF-8}"
exec "\${BIN}" "\$@"
LAUNCHER
chmod +x "${APP}/Contents/MacOS/${NAME}"

# let Finder/Spotlight pick up the new bundle and icon
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
[ -x "${LSREGISTER}" ] && "${LSREGISTER}" -f "${APP}" || true

echo "Created ${APP} (CherryTree ${VERSION} from ${REPO}/build)"
